app/controllers/EntriesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Entries;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\helpers\Url;
use yii\data\ActiveDataProvider;

/**
 * EntriesController implements the CRUD actions for Entries model.
 */
class EntriesController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Entries models.
     * @return mixed
     */
    public function actionIndex()
    {
        $entries = Entries::find()
        ->orderBy(['(creation_date)' => SORT_DESC]);     
        
        $dataProvider = new ActiveDataProvider([
            'query' => $entries,
            'pagination' => [
                'pageSize' => 3,
            ],
        ]);

        return $this->render('index', [            
            'dataProvider' => $dataProvider            
        ]);
    }

    /**
     * Displays a single Entries model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Entries model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(Url::to(['user/login']), 302);
        }
        $model = new Entries();
        
        if ($model->load(Yii::$app->request->post())) {
            $model->creation_date = date("Y-m-d H:i:s");
            $model->author = $_SESSION["__id"];
            if ($model->save()) {
                Yii::$app->session->setFlash('info', 'Post created!');
                return $this->redirect(['index']);
            }
            Yii::$app->session->setFlash('error', 'Oops something goes wrong!');            
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Entries model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
               Yii::$app->session->setFlash('info', 'Post updated!');
                return $this->redirect(['index']);
            }

            Yii::$app->session->setFlash('error', 'Oops something goes wrong!');
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Entries model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Entries model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Entries the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Entries::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

app/controllers/ProfileController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\data\ActiveDataProvider;
use yii\filters\VerbFilter;
use dektrium\user\models\Profile;
use dektrium\user\models\User;
use app\models\Entries;

class ProfileController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Show user profile
     * @return mixed
     */
    public function actionShow($id)
    {
        $profile = $this->findModel($id);
        
        $user = User::findOne($profile->user_id);

        $repositories = [];         
        try{
            $client = new \Github\Client();
            $repositories = $client->api('user')->repositories($user->username); 
        } catch (\Exception $e) {
            echo $e->getMessage(), "\n";
        }
                     

        $entries = Entries::find()
        ->where('author=:author')
        ->addParams([':author' => $profile->user_id])
        ->orderBy(['(creation_date)' => SORT_DESC]);     
        
        $dataProvider = new ActiveDataProvider([
            'query' => $entries,
            'pagination' => [
                'pageSize' => 3,
            ],
        ]);

        return $this->render('show', [
            'profile' => $profile,
            'dataProvider' => $dataProvider,
            'repositories' => $repositories
        ]);
    }

    protected function findModel($id)
    {
        if (($model = Profile::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

app/views/entries/_entry.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
?>

<div class="list-group-item list-group-item-action flex-column align-items-start">    
  <h5 class="mb-1"><?= Html::encode($model->title) ?></h5>              
  <p class="mb-1"><?= HtmlPurifier::process($model->content) ?></p>    
  <small><?= Html::encode($model->creation_date) ?></small>
  <div align="right"><h4><?= Html::a(Html::encode($model->author0->username), ['/profile/show', 'id'=>$model->author] ) ?></h4></div>  
<?php 
if (isset($_SESSION["__id"]) && $model->author == $_SESSION["__id"]){
  echo Html::a('edit entry', ['/entries/update', 'id'=>$model->id], ['class'=>'glyphicon glyphicon-edit']);
}
?>
</div>

app/views/entries/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Entries */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="entries-form">

    <?php $form = ActiveForm::begin(); ?>    

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'content')->textarea(['rows' => 6]) ?>    

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

app/views/entries/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Entries */

$this->title = 'New post';
$this->params['breadcrumbs'][] = ['label' => 'Entries', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="entries-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

app/views/entries/index.php
<?php 
use yii\widgets\ListView;
use yii\helpers\Html;


echo "<div align=\"right\">".Html::a('New post', ['/entries/create'], ['class'=>'btn btn-primary'])."</div>";
?>
<div class="list-group">
<?php
echo ListView::widget([
    'dataProvider' => $dataProvider,
    'itemView' => '_entry',
]);
?>
</div>

app/views/entries/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Entries */

$this->title = 'Update Entries: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Entries', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="entries-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>